INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Super Beans", "Horticulture", 150.00, "March 3 2017", "August 20 2017");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Give Whales Hands", "Science", 2000000.00, "October 12 2018","August 4 2056");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Reshoot Game of Thrones finale", "Television", 50000.00, "January 1 2020", "July 3 2020");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Drug Sniffing Owls", "Science", 80000.00, "November 2 2019", "April 3 2021");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Divide By Zero", "Mathematics", 200.00, "January 20 12 BC", " June 6 4001 AD");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Too Much Zuccini", "Horticulture", 1000.00, "May 13 2018", "September 3 2018");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Rock and Roll Nightmare TV Show", "Television", 300000.00, "October 31 2019", "October 31 2020");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Break Some Rocks", "Science", 20.00, "Today", "Tomorrow");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Find out if Kiki loves me", 1000.00, "Music", "July 2018", "August 2020");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Dig to China", "Science", 10000.00, "August 11 2017", "November 12 2020");

INSERT INTO users (name, age) VALUES ("Byron", 12);
INSERT INTO users (name, age) VALUES ("Nemo", 100);
INSERT INTO users (name, age) VALUES ("Grog", 25);
INSERT INTO users (name, age) VALUES ("Aubrey", 35);
INSERT INTO users (name, age) VALUES ("Reagan", 82);
INSERT INTO users (name, age) VALUES ("Cordelia", 50);
INSERT INTO users (name, age) VALUES ("Cecilia", 54);
INSERT INTO users (name, age) VALUES ("Beatrice", 34);
INSERT INTO users (name, age) VALUES ("Harry", 23);
INSERT INTO users (name, age) VALUES ("Igor", 44);
INSERT INTO users (name, age) VALUES ("Stefan", 70);
INSERT INTO users (name, age) VALUES ("Freida", 11);
INSERT INTO users (name, age) VALUES ("Beto", 26);
INSERT INTO users (name, age) VALUES ("Terrance", 26);
INSERT INTO users (name, age) VALUES ("Lisa", 56);
INSERT INTO users (name, age) VALUES ("Kiki", 24);
INSERT INTO users (name, age) VALUES ("Whale", 50);
INSERT INTO users (name, age) VALUES ("Fifi", 16);
INSERT INTO users (name, age) VALUES ("Beebee", 10);
INSERT INTO users (name, age) VALUES ("Charles", 66);

INSERT INTO pledges (amount, user_id, project_id) VALUES (30, 16, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (300, 17, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10000, 2, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 19, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 3, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (40, 15, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (30, 4, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 14, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 12, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 8, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5000, 8, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 14, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 12, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (70, 7, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5, 4, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10000, 10, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 10, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (800, 7, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (800, 4, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 12, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 8, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5000, 8, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 14, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 12, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (77, 13, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (55, 4, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10000, 10, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (90, 10, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 11, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 5, 4);
